swap to a python based config file
nullpixel1/steamb0at pull request #4
Opened 2017-04-04 05:40 UTC by mralext20

2017-04-04 16:37 UTC, nullpixel1 commented
i love yaml tho

2017-04-04 18:49 UTC, mralext20 commented
how bout now bby

i actually got a feature working

2017-04-05 03:37 UTC, nullpixel requested changes

2017-04-05 03:37 UTC, nullpixel1 commented on cogs/events.py
> +        log_channel = self.bot.get_channel(config.guilds[message.server.id]['server-log'])
* You could make this global to the class. 
* Why doesn't the bot automatically find and make one if it does not exist? Could that be a command?

2017-04-05 03:37 UTC, nullpixel1 commented on cogs/events.py
> +        log_message = ":wastebasket: " + message.author.name + "#" + message.author.discriminator + "`" + message.author.id + "` deleted from channel #" + message.channel.name + "\n" + message.conten
Could use .format() here for a cleaner look?

2017-04-05 18:00 UTC, nullpixel1 commented
Okay, merging. When you have time, I'd love a !setup command to automatically make all required channels and add them to the config.

Still hurt you took away my yaml 😦

2017-04-05 18:00 UTC, nullpixel approved these changes

2017-04-05 18:00 UTC, merged